apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  labels:
spec:
  selector:
    matchLabels:
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: "{{ .IAMRoles.K8sSecretSyncer }}"
      labels:
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        env:
        - name: AWS_REGION
          value: '{{ default "us-east-1" .K8sSecretSyncer.Region }}'
        image: "contentful/k8s-secret-syncer{{ .K8sSecretSyncer.ImageTag }}"
        name: k8s-secret-syncer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
