apiVersion: secrets.contentful.com/v1
kind: SyncedSecret
metadata:
  name: syncedsecret-sample-ks
  namespace: k8s-secret-syncer
spec:
  secretMetadata:
    name: demo-service-secret
    namespace: k8s-secret-syncer
    annotations:
      randomkey: randomval
  data:
    DB_NAME: database_name
    DB_PASS: database_pass
  secretid: secretsyncer/secret/sample
